#!/bin/bash

RELAYER_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
RELAYER_CONF="$HOME/.relayer"
GAIA_CONF="$(pwd)/data"
CONFIG_DATA="$(pwd)/data"

# Ensure user understands what will be deleted
if ([[ -d $RELAYER_CONF ]] || [[ -d $GAIA_CONF ]]) && [[ ! "$1" == "skip" ]]; then
  read -p "$0 will delete \$HOME/.relayer and \$(pwd)/data folder. Do you wish to continue? (y/n): " -n 1 -r
  echo
  if [[ ! $REPLY =~ ^[Yy]$ ]]; then
      exit 1
  fi
fi

cd $RELAYER_DIR
rm -rf $RELAYER_CONF &> /dev/null
pwd
bash scripts/three-chainz "skip"

echo "waiting for blocks..."
sleep 2

rly tx link demo -d -o 5s
rly tx link demo2 -d -o 5s
#rly start demo > $CONFIG_DATA/rly-0.log 2>&1 &
#rly start demo2 > $CONFIG_DATA/rly-1.log 2>&1 &
echo "Initial balances"
echo "balance 0 $(rly q bal ibc-0)"
echo "balance 1 $(rly q bal ibc-1)"
echo "balance 2 $(rly q bal ibc-2)"
echo
echo "Packet receiver field: $(rly keys show ibc-1)|transfer/channel-1:$(rly keys show ibc-2)"
rly tx transfer ibc-0 ibc-1 10000000000samoleans "raw:$(rly keys show ibc-1)|transfer/channel-1:$(rly keys show ibc-2)"
sleep 2
rly tx relay-packets demo -d > $CONFIG_DATA/rly-0.log 2>&1 &
sleep 2
rly tx relay-acknowledgements demo -d > $CONFIG_DATA/rly-0.log 2>&1 &
sleep 10
rly tx relay-packets demo2 -d > $CONFIG_DATA/rly-1.log 2>&1 &
sleep 2
rly tx relay-acknowledgements demo2 -d > $CONFIG_DATA/rly-1.log 2>&1 &
echo
sleep 10
echo "Balances after packet is sent to ibc-1"
echo "balance 0 $(rly q bal ibc-0)"
echo "balance 1 $(rly q bal ibc-1)"
echo "balance 2 $(rly q bal ibc-2)"
sleep 10
echo "Balances after packet is sent from ibc-1 to ibc-2"
echo "balance 0 $(rly q bal ibc-0)"
echo "balance 1 $(rly q bal ibc-1)"
echo "balance 2 $(rly q bal ibc-2)"
echo "################## relayer ibc-0 -> ibc-1 logs #####################"
cat $CONFIG_DATA/rly-0.log
echo "################## relayer ibc-0 -> ibc-1 logs #####################"
cat $CONFIG_DATA/rly-1.log

#go run main.go tx transfer ibc-0 ibc-1 1000samoleans $(go run main.go ch addr ibc-1)
#go run main.go tx transfer ibc-1 ibc-2 1000samoleans $(go run main.go ch addr ibc-2)
#go run main.go tx transfer ibc-2 ibc-1 1000samoleans $(go run main.go ch addr ibc-1)
#go run main.go tx transfer ibc-1 ibc-0 1000samoleans $(go run main.go ch addr ibc-0)
#sleep 2
#go run main.go tx relay-packets demo -d
#sleep 2
#go run main.go tx relay-acknowledgements demo -d