#!/bin/bash

SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
CONFIG_DATA="$(pwd)/data"

chainid0=ibc-0
chainid1=ibc-1
chainid2=ibc-2

echo "Building Relayer..."
make install

echo "Generating rly configuration..."
rly config init
rly config add-chains configs/three/chains/

SEED0=$(jq -r '.mnemonic' $CONFIG_DATA/$chainid0/key_seed.json)
SEED1=$(jq -r '.mnemonic' $CONFIG_DATA/$chainid1/key_seed.json)
SEED2=$(jq -r '.mnemonic' $CONFIG_DATA/$chainid2/key_seed.json)

echo "Key $(rly keys restore $chainid0 testkey "$SEED0") imported from $chainid0 to relayer..."
echo "Key $(rly keys restore $chainid1 testkey "$SEED1") imported from $chainid1 to relayer..."
echo "Key $(rly keys restore $chainid2 testkey "$SEED2") imported from $chainid2 to relayer..."

rly config add-paths configs/three/paths/