#!/bin/bash

SCRIPTDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
CONFIG_DATA="$(pwd)/data"

echo "Building Relayer..."
make install

echo "Generating rly configuration..."
rly config init
rly config add-chains configs/three/chains/

SEED0=$(jq -r '.mnemonic' $CONFIG_DATA/ibc-0/key_seed.json)
SEED1=$(jq -r '.mnemonic' $CONFIG_DATA/ibc-1/key_seed.json)
SEED2=$(jq -r '.mnemonic' $CONFIG_DATA/ibc-2/key_seed.json)

echo "Key $(rly keys restore ibc-0 testkey "$SEED0") imported from ibc-0 to relayer..."
echo "Key $(rly keys restore ibc-1 testkey "$SEED1") imported from ibc-1 to relayer..."
echo "Key $(rly keys restore ibc-2 testkey "$SEED2") imported from ibc-2 to relayer..."

rly config add-paths configs/three/paths/